### PR TITLE
Added embry

### LINKED ISSUE #69: [emby] Port from truecharts
# Details

**Image name:**

Emby

I am opening this issue to state that I will be attempting to port emby over from truecharts so that I can become familiar with the process.

https://github.com/truecharts/apps/tree/staging/.containers/apps/emby

**Anything else you would like to add:**

N/A

**Additional Information:**

N/A

### PR DESCRIPTION
**Pull request by nicholaswilde**
Signed-off-by: Nicholas Wilde <ncwilde43@gmail.com>

**Description of the change**

Ported embry over from truecharts

**Benefits**

Additional chart to use

**Possible drawbacks**

None

**Applicable issues**

- fixes #69

**Additional information**

Added `arm64` architecture and used `plex-media-server` as a reference.

### CODE REVIEW

**Comment by nicholaswilde** [comment]
Bah, I need to fix GOSS.

**Comment by onedr0p** [comment]
Takes me a few tries to get the goss test right too 😅

**Comment by nicholaswilde** [comment]
I couldn't get the ports to work but I was able to check the process. I will add this to the docs and we can fix the ports later?

**Comment by onedr0p** [comment]
Did you try tcp instead of tcp6?

**Comment by nicholaswilde** [comment]
> Did you try tcp instead of tcp6?

I did but I will keep playing around with it.

**Comment by onedr0p** [comment]
We can merge it and figure it out later too, let me know 🙂

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
