### PR TITLE
Update lidarr-nightly

### PR DESCRIPTION
**Pull request by igas**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

### CODE REVIEW

**Comment by bjw-s** [comment]
Thanks for taking the time to create this PR! Unfortunately, the content of the `VERSION` file is auto-generated by the `latest-version.sh` script.
I just ran that manually and it still  returns `1.0.0.2255`. This means that your change would be overwritten the next time our scheduled job triggers the update script.

**Comment by igas** [comment]
Thanks @bjw-s, do you know who handles upstream json? https://github.com/linuxserver/docker-lidarr/pkgs/container/lidarr linux server as well as inside lidarr System/Updates there are new versions.

**Comment by bjw-s** [comment]
If we change our latest-version.sh script to query the Azure DevOps directly we can bypass their `servarr.com` api:

```console
#!/usr/bin/env bash

version_regex='1\\.[0-9]+\\.[0-9]+\\.[0-9]+'
api_url='https://dev.azure.com/Lidarr/Lidarr/_apis/build/builds'

version=$(curl -sX GET "${api_url}" | jq --raw-output "[.value[] | select(.buildNumber | test(\"${version_regex}\")) | .buildNumber] | sort | reverse | first")
version="${version#*v}"
version="${version#*release-}"
printf "%s" "${version}"
```

**Comment by bjw-s** [comment]
Just had a talk with @onedr0p and he's going to update the script for the other images, including this one.

**Comment by onedr0p** [comment]
I have updated this, we should be good now. Thanks for the report!

https://github.com/k8s-at-home/container-images/commit/bc9b661139d56371eadd2a17c72e1aff47c7cac2

**Comment by bjw-s** [comment]
The new builds are up! 🥳

**Pull request closed without merging**
