### PR TITLE
New container - cert-manager webhook dnsmadeeasy

### PR DESCRIPTION
**Pull request by angelnu**
**Description of the change**

Add cert-manager webhook for dnsmadeeasy

**Benefits**

Allow using DNS resolver with LEt´s Encrypt and dnsmadeeasy

**Possible drawbacks**

None

**Applicable issues**

NA

**Additional information**

Since all sources are added here there is no external repo. To ensure the package still builds with latest golang a weekly github action is used (that does not push).

### CODE REVIEW

**Comment by bjw-s** [comment]
I pinged @onedr0p on Discord about this, but might as well add it to the discussion here.

In general I think it looks good, but what I'm not certain about is the fact that webhook sources and the image are now in the same repo, making the k8s-at-home org "responsible" for the webhook code as well.

**Comment by angelnu** [comment]
@bjw-s @onedr0p - I am the developer of the webhook and would be glad to support it here directly if that helps. Since it is to be consumed only together with k8s and the corresponding helm chart there is no use-case as plain docker image.

Will follow here and Discord what is the feedback.

**Comment by angelnu** [comment]
I re-based on the common Ubuntu image

**Comment by onedr0p** [comment]
I would be happier if we hosted this as it's own repo like k8s-at-home/webhook-dnsmadeeasy for example. This feels like it's own little project with it's own development lifecycle. If we all agree I can create a repo and @angelnu you can migrate this PR there.

**Comment by billimek** [comment]
Agreed. It seems that original code to build a binary should be in a dedicated repo and the glue to containerize it should be in this repo.

**Comment by onedr0p** [comment]
> Agreed. It seems that original code to build a binary should be in a dedicated repo and the glue to containerize it should be in this repo. 

I was thinking about having a GH workflow to build the container in the k8s-at-home/webhook-dnsmadeeasy repo too. Let it be isolated like it's own project.

**Comment by onedr0p** [comment]
@angelnu I created a repo https://github.com/k8s-at-home/dnsmadeeasy-webhook

**Comment by angelnu** [comment]
Thanks @onedr0p - I will move it there.

That also allows me to add my test credentials as secret.

I wonder if I should split the build in binary and container since today I do both. I need to see what actions exits for golang CI to ideally build a new binary when the used libraries change.

**Comment by onedr0p** [comment]
You don't have to attach binaries to the release since this will only be used as a container right?

**Comment by angelnu** [comment]
Correct, there is no use case beyond the container & helm-chart.

Are suggesting @onedr0p to directly put the container in the new repo and nothing here? I can take the docker CI from here into the new repo....

**Comment by onedr0p** [comment]
Yes, that new repo can hold all the source code and building / publishing of the image.

**Comment by angelnu** [comment]
Good - then closing here and will add to the other repo. Then I will submit the PR for the Helm chart.

**Pull request closed without merging**
