### PR TITLE
[wireguard] feat: install jq

### PR DESCRIPTION
**Pull request by mdallaire**
**Description of the change**

Add jq to the list of packages installed via apt

**Benefits**

Allows parsing json in livenessProbe. Currently I am using 
```
livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(curl -s https://am.i.mullvad.net/country) = '${SECRET_VPN_COUNTRY}' ]; then exit 0; else exit $?; fi
```
Adding jq allows to parse the more complete [https://am.i.mullvad.net/json](https://am.i.mullvad.net/json) and explicitly check for "mullvad_exit_ip" to check if the VPN is up. This also allows to safely use VPN exits in the same country.
```
livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(curl -s https://am.i.mullvad.net/json | jq '.mullvad_exit_ip') = 'true' ]; then exit 0; else exit $?; fi
```

**Possible drawbacks**

The image is a bit bigger.

**Applicable issues**

- fixes #

**Additional information**

### CODE REVIEW

**Comment by onedr0p** [comment]
Looks like a good idea, thanks!

**Comment by bjw-s** [comment]
Not sure why this is needed thougb? Because `jq` (and `curl`) should already be in the base image:

https://github.com/k8s-at-home/container-images/blob/main/base/ubuntu/Dockerfile#L46

**Comment by mdallaire** [comment]
That is weird, I was getting command not found jq when testing earlier... I have an internet outage right now so can't confirm on the wireguard container but I also get command not found for jq on the k8s-at-home sonarr container.

**Comment by bjw-s** [comment]
Doh... it looks like I missed something quite important in the base image:
https://github.com/k8s-at-home/container-images/blob/main/base/ubuntu/Dockerfile#L73
We actually remove it further down the `Dockerfile` 😂. Sorry about the confusion!

**Pull request merged**
